services:
  api-test:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db-test
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ENV=test
    command: ["./wait-for-db.sh", "python", "app.py"]
    networks:
      - jenkins-net
    container_name: api-test
  db-test:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - jenkins-net
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

networks:
  jenkins-net:
    external: true